spring:
  profiles:
    active: ${springProfilesActive:test}  # default test ??
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # update
  datasource:
    url: jdbc:mysql://localhost:3306/service_account
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(E9z40SdZdMVFDbg5ezBq1Q==)
    password: ENC(HoolX7GcqlA0CZDiZ99jnJ1RXpSgujAW)
  sql:
    init:
      mode: never

jasypt:
  encryptor:
    bean: jasyptEncryptor

server:
  port: 9081
  shutdown: graceful

grpc:
  server:
    port: 10091
